### ISSUE TITLE
Clarification on IM-GAN vs IM-AE

### ISSUE THREAD

**Issue by 5agado** [czq142857/IM-NET#14]
I was checking the paper and playing with the code, and I was curious about the details regarding the GAN version vs the autoencoder version. The supplement material seems to show better interpolation results for GAN, but in the code I see that the GAN version (ZGAN class in modelz.py) is not even used for inference in the main, and instead it just used to fetch a random z and fed it to the AE. Any particular reason for this?

Also wights for the IM-GAN are not provided, am I correct?

**Comment by czq142857** [comment]
We used a latent GAN in our paper, because it can be trained much faster than a common GAN.

In a common GAN framework:
random code -> Generator -> output shape.

In a latent GAN framework:
random code -> Generator -> output code -> Shape Decoder -> output shape.

Therefore you saw what you saw in the code.

This repo is dedicated for shape autoencoding and single view reconstruction on the 13 ShapeNet categories. Although you could train a GAN with the provided code, we do not provide pretrained weights.

If you need the weights, please go to the original implementation:
https://github.com/czq142857/implicit-decoder.

**Comment by 5agado** [comment]
Thank you for the clarification, that makes sense.
