### ISSUE TITLE
Generate my own data "batch_size exceeded!"

### ISSUE THREAD

**Issue by Howardyangyixuan** [czq142857/IM-NET#16]
Hi Chen, thank you for sharing the code.
I am trying to train the network with my own data. But when I used 2_gather_256vox_16_32_64.py to generate training data from my 256^3 voxels, I got warnings like "64-- batch_size exceeded! and 32-- batch_size exceeded!" and "2_test_hdf5.py" generate something like this
[3_p64_3](https://user-images.githubusercontent.com/44062498/130002419-1c3df3dc-0ffe-4b5f-91c8-b399a5a901fb.png)
It seems something is wrong but I haven't found out the problem. Could you please give me some hints or have you met this before? I'm eager to know how to fix it.

Great Thanks!

**Comment by czq142857** [comment]
Hi,

This is because the maximum number of points are sampled for the shape but they are still unable to cover the entire shape. For example, you may need 20000 points to cover the entire shape but the upper bound set in the code is 16384, then you will get a "batch_size exceeded" warning.

You can safely ignore the warnings if only a small portion of the shapes have such warnings.

If you want to change the upper bounds, find the following lines of code at each script and change them to some larger numbers.

```
batch_size_1 = 16*16*16
batch_size_2 = 16*16*16
batch_size_3 = 16*16*16*4
```

**Comment by Howardyangyixuan** [comment]
Thank you very much for your quick and detailed reply! I got it at once.
So for the best performance of IM-Net and also for BSP-Net should I use the maximum possible amount to prevent "batch_size exceeded" regardless of the time of trainig?
And have you ever test how the growing batch_size will slow down the training of the network?

**Comment by czq142857** [comment]
I have never tested other options so I am not sure how they can influence the training.

**Comment by Howardyangyixuan** [comment]
Then I'll try it by myself. Really appreciate your fast response. Great thanks!
