### ISSUE TITLE
MSE, IoU, symmetric Chamfer distance (CD)

### ISSUE THREAD

**Issue by czsc123** [czq142857/IM-NET#7]
Hi Zhiqin,

Thanks for the great work.
Can you provide the codes you use of the MSE, IoU, symmetric Chamfer distance (CD) for model evaluation?

Best regards,
czsc

**Comment by czq142857** [comment]
For symmetric Chamfer distance (CD), you can check this:
https://github.com/czq142857/BSP-NET-original/tree/master/evaluation
The implementation is simple, you can easily modify the code for your own use.

MSE and IOU are done on voxels. And since the testing function in the code is already giving you the output voxels, you can add a few lines to compute the MSE and IOU against the ground truth. It is not provided in the implementation as it is really trivial to add. Please try to code it by yourself.

Best,
Zhiqin

**Comment by czsc123** [comment]
Thank you, i will try to code it by myself.

**Comment by lixiang-ucas** [comment]
Hello guys! @czq142857 @czsc123  I still have some questions regarding IoU calculation. In the current code, the predicted voxels have sizes of (256+2)*(256+2)*(256+2), while the input voxels are of size 16/32/64. Are you doing downsampling for the predicted voxels before calculating IoUs?

**Comment by czq142857** [comment]
Yes, please do downsampling using max-pooling. The actual output is 256, so please remove the 1-padding (1--256--1).
